name: Use the data

on:
  workflow_run:
    workflows: [Validate]
    types:
      - completed

jobs:
  post-comment:
     runs-on: ubuntu-latest
     steps:
      - name: 'Post PR comment'
        uses: mshick/add-pr-comment@v2
        if: github.event_name == 'pull_request'
        with:
          message-id: ${{ github.sha }}
          message: |
            **Snapshot Tests**
            **API 23**: [Report](https://happo.io/a/27/report/${{ github.sha }}-android23) [Diff](https://happo.io/a/27/p/27/compare/master-android23/${{ github.sha }}-android23)
            **API 31**: [Report](https://happo.io/a/27/report/${{ github.sha }}-android31) [Diff](https://happo.io/a/27/p/27/compare/master-android31/${{ github.sha }}-android31)